// 模拟数据 - 开源技术生态系统
const nodes = [
            { id: "JavaScript", group: 0, description: "Web核心编程语言", popularity: 100 },
            { id: "React", group: 0, description: "用于构建用户界面的JavaScript库", popularity: 95 },
            { id: "Vue.js", group: 0, description: "渐进式JavaScript框架", popularity: 85 },
            { id: "Angular", group: 0, description: "基于TypeScript的Web应用框架", popularity: 80 },
            { id: "Node.js", group: 5, description: "JavaScript运行时环境", popularity: 90 },
            { id: "Express", group: 5, description: "Node.js Web应用框架", popularity: 85 },
            { id: "TypeScript", group: 0, description: "JavaScript的类型化超集", popularity: 85 },
            { id: "Webpack", group: 2, description: "JavaScript模块打包器", popularity: 90 },
            { id: "Babel", group: 2, description: "JavaScript编译器", popularity: 85 },
            { id: "Jest", group: 3, description: "JavaScript测试框架", popularity: 80 },
            { id: "Mocha", group: 3, description: "Node.js测试框架", popularity: 75 },
            { id: "Redux", group: 4, description: "JavaScript状态管理库", popularity: 80 },
            { id: "Vuex", group: 4, description: "Vue.js的状态管理库", popularity: 75 },
            { id: "CSS3", group: 1, description: "层叠样式表最新标准", popularity: 100 },
            { id: "Sass", group: 1, description: "CSS预处理器", popularity: 85 },
            { id: "Less", group: 1, description: "CSS预处理器", popularity: 70 },
            { id: "Bootstrap", group: 1, description: "前端CSS框架", popularity: 90 },
            { id: "Tailwind CSS", group: 1, description: "实用优先的CSS框架", popularity: 85 },
            { id: "MongoDB", group: 6, description: "NoSQL文档数据库", popularity: 80 },
            { id: "PostgreSQL", group: 6, description: "开源关系型数据库", popularity: 85 },
            { id: "GraphQL", group: 7, description: "API查询语言", popularity: 80 },
            { id: "REST", group: 7, description: "API设计架构", popularity: 95 },
            { id: "D3.js", group: 0, description: "数据驱动文档的JavaScript库", popularity: 75 },
            { id: "Next.js", group: 5, description: "React框架，支持服务端渲染", popularity: 85 },
            { id: "Nuxt.js", group: 5, description: "Vue框架，支持服务端渲染", popularity: 80 },
            { id: "Git", group: 2, description: "分布式版本控制系统", popularity: 95 },
            { id: "npm", group: 2, description: "JavaScript包管理器", popularity: 95 },
            { id: "Yarn", group: 2, description: "JavaScript包管理器", popularity: 80 },
        ];
        
        const links = [
            { source: "React", target: "JavaScript", value: 10 },
            { source: "Vue.js", target: "JavaScript", value: 10 },
            { source: "Angular", target: "JavaScript", value: 10 },
            { source: "Angular", target: "TypeScript", value: 8 },
            { source: "React", target: "Node.js", value: 7 },
            { source: "Express", target: "Node.js", value: 10 },
            { source: "Next.js", target: "React", value: 9 },
            { source: "Next.js", target: "Node.js", value: 8 },
            { source: "Nuxt.js", target: "Vue.js", value: 9 },
            { source: "Nuxt.js", target: "Node.js", value: 8 },
            { source: "React", target: "Redux", value: 8 },
            { source: "Vue.js", target: "Vuex", value: 8 },
            { source: "React", target: "Webpack", value: 7 },
            { source: "Vue.js", target: "Webpack", value: 7 },
            { source: "Angular", target: "Webpack", value: 7 },
            { source: "React", target: "Babel", value: 8 },
            { source: "Vue.js", target: "Babel", value: 8 },
            { source: "React", target: "Jest", value: 7 },
            { source: "Node.js", target: "Express", value: 9 },
            { source: "JavaScript", target: "TypeScript", value: 9 },
            { source: "CSS3", target: "Sass", value: 8 },
            { source: "CSS3", target: "Less", value: 7 },
            { source: "CSS3", target: "Bootstrap", value: 8 },
            { source: "CSS3", target: "Tailwind CSS", value: 8 },
            { source: "React", target: "CSS3", value: 7 },
            { source: "Vue.js", target: "CSS3", value: 7 },
            { source: "Angular", target: "CSS3", value: 7 },
            { source: "Node.js", target: "MongoDB", value: 7 },
            { source: "Node.js", target: "PostgreSQL", value: 7 },
            { source: "Express", target: "MongoDB", value: 7 },
            { source: "Express", target: "PostgreSQL", value: 7 },
            { source: "REST", target: "Express", value: 9 },
            { source: "GraphQL", target: "Express", value: 8 },
            { source: "React", target: "REST", value: 7 },
            { source: "React", target: "GraphQL", value: 7 },
            { source: "D3.js", target: "JavaScript", value: 9 },
            { source: "Git", target: "Node.js", value: 8 },
            { source: "npm", target: "Node.js", value: 10 },
            { source: "Yarn", target: "Node.js", value: 9 },
            { source: "React", target: "npm", value: 8 },
            { source: "Vue.js", target: "npm", value: 8 },
            { source: "Angular", target: "npm", value: 8 },
            { source: 'Mocha', target: 'Node.js', value: 8 },
        ];

// export { nodes, links };